[package]
name = "graphstuff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.6.4"
rand = "0.9.0-alpha.0"
petgraph-gen = "0.1.3"